language: node_js
node_js:
  - "8.15.1"

cache: npm
directories:
  # we also need to cache folder with Cypress binary
  - ~/.cache

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g cypress"

install:
  - "meteor npm install"

script:
  - "npm run test:prod"