language: node_js
node_js:
  - "8.15.1"

cache: npm
directories:
  # cypress
  - ~/.cache
  # meteor
  - ~/.meteor
  - .meteor/local

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g cypress"

install:
  - "meteor npm install"

script:
  - "npm run test:prod"